### PR TITLE
Added PyOhio to upcoming events

### PR DESCRIPTION
**Pull request by kattni**

### CODE REVIEW

**Comment by tannewt** [comment]
Please add to template too

**Comment by kattni** [comment]
I don't understand what you mean by "add to template".

**Comment by tannewt** [comment]
Sorry my slow typing makes me terse. Add here too: https://github.com/adafruit/circuitpython-weekly-newsletter/blob/gh-pages/_drafts/template.md

**Comment by kattni** [comment]
Closing. Added directly.

**Pull request closed without merging**
