### PR TITLE
Update with some recent MicroPython news

### PR DESCRIPTION
**Pull request by mattytrentini**
I've added a number of MicroPython links, mostly news collected over the past handful of weeks.
Feel free to edit/modify/discard!

### CODE REVIEW

**Comment by ladyada** [comment]
thanks @mattytrentini !

**Review by TheKitty — APPROVED** [review]

**Comment by TheKitty** [comment]
@mattytrentini - thank you very, very much for the contributions!! They are merged and scheduled for tomorrow's edition. We'd appreciate newsworthy contributions at any time. Images should be a max of 550 in the final edition but in PRs can be arbitrarily big so they can be used in the Python on Hardware video news (where larger images work better). Feel free to contact me Twitter @anne_engineer or tag #CircuitPython and #MicroPython (I check both).

**Comment by TheKitty** [comment]
@mattytrentini you may always put unformatted material in the Issues also

**Comment by mattytrentini** [comment]
Glad you folks could make use of the posts! Thanks for including them. 

I'll know to include better images along with the PR next time but, in case it's still useful for the PoH video, I've [included the originals]](https://github.com/adafruit/circuitpython-weekly-newsletter/files/5090162/images.zip).

**Pull request merged**
